version: 0.0.{build}
image: Visual Studio 2017 RC
nuget:
  project_feed: true
build:
  project: src/EnumGenie.sln
  publish_nuget: true
  verbosity: minimal
before_build:
  - nuget restore
deploy:
- provider: NuGet
  api_key:
    secure: X2uz65l0BYTO4wu2eDQK06cp6Ad7DTwwd6/7kTanRy9lf3x70B9D3mJmjnZpNtoh
  on:
    branch: master