version: 0.0.{build}
image: Visual Studio 2017 RC
nuget:
  project_feed: true
init:
  - ps: >-
      reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,31bf3856ad364e35" /f

      if ($env:PROCESSOR_ARCHITECTURE -eq "AMD64")
      {
        reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,31bf3856ad364e35" /f
      }
build:
  project: src/EnumGenie.sln
  publish_nuget: true
  verbosity: minimal
before_build:
  - dotnet restore src\EnumGenie.sln
build_script:
  - msbuild "./src/EnumGenie.Core/EnumGenie.Core.csproj" /verbosity:minimal /t:pack /p:Configuration=Release /p:PackageVersion={version}
  - msbuild "./src/EnumGenie.TypeScript/EnumGenie.TypeScript.csproj" /verbosity:minimal /t:pack /p:Configuration=Release /p:PackageVersion={version}
deploy:
- provider: NuGet
  api_key:
    secure: X2uz65l0BYTO4wu2eDQK06cp6Ad7DTwwd6/7kTanRy9lf3x70B9D3mJmjnZpNtoh
  on:
    branch: master
artifacts:
  - path: '**\*.nupkg'