version: 0.0.{build}
image: Visual Studio 2017 RC
nuget:
  project_feed: true
build:
  project: src/EnumGenie.sln
  publish_nuget: true
  verbosity: minimal
before_build:
  - dotnet restore src\EnumGenie.sln
  - sn -Vr NuGet.Build.Tasks.Pack,31bf3856ad364e35
  - sn -Vr NuGet.Commands,31bf3856ad364e35
  - sn -Vr NuGet.LibraryModel,31bf3856ad364e35
build_script:
  - msbuild "./src/EnumGenie.Core/EnumGenie.Core.csproj" /verbosity:minimal /t:pack /p:Configuration=Release
  - msbuild "./src/EnumGenie.TypeScript/EnumGenie.TypeScript.csproj" /verbosity:minimal /t:pack /p:Configuration=Release
after_build:
  - sn -Vu NuGet.Build.Tasks.Pack,31bf3856ad364e35
  - sn -Vu NuGet.Commands,31bf3856ad364e35
  - sn -Vu NuGet.LibraryModel,31bf3856ad364e35
deploy:
- provider: NuGet
  api_key:
    secure: X2uz65l0BYTO4wu2eDQK06cp6Ad7DTwwd6/7kTanRy9lf3x70B9D3mJmjnZpNtoh
  on:
    branch: master
artifacts:
  - path: '**\*.nupkg'